title: IZBR
author: Isaac Basque-Rice

description: >-
  Hi! My name is Isaac Basque-Rice, I'm a fourth year Ethical Hacking student at Abertay University in Dundee, and this website is a repository for all the cool stuff I've done, enjoy!

theme: jekyll-theme-midnight

email: izbr@protonmail.com
github_username: IBRice101
twitter_username: IBRice101
linkedin_username: izbr
