title: IZBR
author: Isaac Basque-Rice

description: >-
  Hi! My name is Isaac Basque-Rice, I'm A Security Engineer and former Abertay Ethical Hacker, and this website is a repository for all the cool stuff I've done, enjoy!

theme: jekyll-theme-midnight

email: izbr@protonmail.com
github_username: IBRice101
twitter_username: IBRice101
linkedin_username: izbr
