title: izbr's Infodump
author: Isaac Basque-Rice

theme: jekyll-theme-midnight

email: izbr [at] protonmail [dot] com
github: IBRice101
twitter: IBRice101
linkedin: izbr

share-links-active:
  email: true
  github: true
  twitter: true
  linkedin: true